export const ADD_PLAYER = "PLAYER/ADD";
export const SET_NEXT_PLAYER = "GAME/PLAYER/SET_NEXT";
export const SEND_ANSWER_NO = "ANSWER/SEND_NO";
export const SEND_ANSWER_VICTORY = "ANSWER/SEND_VICTORY";
export const INITIALIZE_APP = "APP/INITIALIZE";
export const APP_DISPATCH = "APP/DISPATCH";
