const ADD_PLAYER = 'PLAYER/ADD';
const SET_NEXT_PLAYER = 'GAME/PLAYER/SET_NEXT';
const SEND_ANSWER_NO = 'ANSWER/SEND_NO';
const SEND_ANSWER_VICTORY = 'ANSWER/SEND_VICTORY';
const INITIALIZE_APP = 'APP/INITIALIZE';
const APP_DISPATCH = 'APP/DISPATCH';
const SOCKET_MESSAGE = 'SOCKET/MESSAGE';

module.exports = {
  ADD_PLAYER,
  SET_NEXT_PLAYER,
  SEND_ANSWER_NO,
  SEND_ANSWER_VICTORY,
  INITIALIZE_APP,
  APP_DISPATCH,
  SOCKET_MESSAGE,
};
